apiVersion: v1
kind: Service
metadata:
  name: covid19-surveillance-file-queue-service
  labels:
    package: covid19surveillance
spec:
  type: LoadBalancer
  selector:
    component: covid19-surveillance-file-queue
  ports:
  - port: 4002
    targetPort: 4002
