apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhis-metadata-config-volume-claim
  labels:
    package: covid19surveillance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 101Mi
