configMapGenerator:
  - name: file-queue-configmap
    files:
      - ./file-queue/config/file-queue-mediator.json

resources:
  - ./mapper/mapper-deployment.yaml
  - ./mapper/mapper-service.yaml
  - ./file-queue/file-queue-deployment.yaml
  - ./file-queue/file-queue-service.yaml
