version: '3.3'

services:
  # container for executing config import scripts for setting up initial config
  openhim-config-importer:
    container_name: covid19-surveillance-openhim-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      OPENHIM_API_HOSTNAME: 'openhim-core'
      OPENHIM_API_PORT: 8080
      OPENHIM_API_USERNAME: 'root@openhim.org'
      OPENHIM_API_PASSWORD: 'instant101'
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - type: volume
        source: instant
        target: /instant
    # This command will only attempt to import the OpenHIM config when the heartbeat responds with a 2xx
    command: sh -c "wait-on -t 60000 https-get://core:8080/heartbeat && node /instant/who-covid19-surveillance-package/docker/importer/volume/openhim/openhimConfig.js"

  # container for executing config import scripts for setting up initial config
  covid19-surveillance-config-importer:
    container_name: covid19-surveillance-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOSTNAME: 'covid19-surveillance-mediator'
      MEDIATOR_API_PORT: 3003
    volumes:
      - type: volume
        source: instant
        target: /instant
    # This command will only attempt to import the covid19-surveillance-mediator config when the uptime endpoint responds with 200
    command: sh -c "wait-on -t 60000 http-get://covid19-surveillance-mediator:3003/uptime && sleep 1 && node /instant/who-covid19-surveillance-package/docker/importer/volume/surveillance-mediator/case-report/endpoint.js && sleep 1 && node /instant/who-covid19-surveillance-package/docker/importer/volume/surveillance-mediator/lab-result/endpoint.js && sleep 1 && node /instant/who-covid19-surveillance-package/docker/importer/volume/surveillance-mediator/case-outcome/endpoint.js"
  
  # container for executing config import scripts for setting up initial config
  dhis2-tracker-populator-config-importer:
    container_name: dhis2-tracker-populator-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOSTNAME: 'dhis2-tracker-populator-mediator'
      MEDIATOR_API_PORT: 3003
    volumes:
      - type: volume
        source: instant
        target: /instant
    # This command will only attempt to import the dhis2-tracker-populator-mediator config when the uptime endpoint responds with 200
    command: sh -c "wait-on -t 60000 http-get://dhis2-tracker-populator-mediator:3003/uptime && sleep 1 && node /instant/who-covid19-surveillance-package/docker/importer/volume/dhis2-tracker-populator/endpoint.js"

  hapi-fhir-config-importer:
    container_name: hapi-fhir-config-importer
    image: jembi/instantohie-hapi-fhir-ig-importer:1.0.1
    restart: on-failure
    environment:
      HAPI_FHIR_BASE_PATH: '/fhir'
      HAPI_FHIR_BASE_URL: 'http://hapi-fhir:8080'
      IG_DEFINITIONS_URL: 'https://openhie.github.io/covid-ig/definitions.json.zip'
    command: sh -c "wait-on -t 60000 http-get://hapi-fhir:8080 && sleep 1 && node index.js"

  # container for executing config import scripts for setting up initial config
  dhis2-config-importer:
    container_name: dhis2-config-importer
    image: jembi/instantohie-config-importer:v1.0.0
    restart: on-failure
    volumes:
      - type: volume
        source: instant
        target: /instant
    # This command will only attempt to import the DHIS2 config when the /api/resources endpoint responds with 200
    command: sh -c "wait-on -t 60000 http-get://dhis-web:8080/api/resources && sleep 1 && node -e 'require(\"/instant/who-covid19-surveillance-package/docker/importer/volume/dhis2/metadata.js\").importMetaData()'"

volumes:
  instant:
    external: true
