version: '3.3'

services:
  # container for executing config import scripts for setting up initial config
  covid19-surveillance-config-importer:
    container_name: covid19-surveillance-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOSTNAME: 'covid19-surveillance-mediator'
      MEDIATOR_API_PORT: 3003
    volumes:
      - type: volume
        source: instant
        target: /instant
    # This command will only attempt to import the covid19-surveillance-mediator config when the uptime endpoint responds with 200
    command: sh -c "wait-on -t 60000 http-get://covid19-surveillance-mediator:3003/uptime && sleep 1 && node /instant/who-covid19-surveillance-package/docker/importer/volume/endpoint.js"

volumes:
  instant:
    external: true
